import React from 'react';
import { 
  Sparkles, 
  ShieldCheck, 
  Activity, 
  TrendingUp, 
  FileCode, 
  CheckCircle2, 
  DollarSign, 
  Layers, 
  ArrowRight 
} from 'lucide-react';

export const PITCH_SLIDES = [
  {
    number: 1,
    tag: "THE CLINICAL PROBLEM",
    title: "Patients Have Reports, Not Understanding",
    subtitle: "The fragmentation of modern pathology and clinical diagnostic records.",
    content: (
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 my-6">
        <div className="p-6 bg-slate-900/90 rounded-2xl border border-slate-800 space-y-3">
          <span className="text-3xl font-black text-rose-400">01</span>
          <h4 className="font-bold text-white text-base">Isolated Snapshots</h4>
          <p className="text-xs text-slate-400 leading-relaxed">
            Every diagnostic visit generates a static paper or PDF slip. Patients collect dozens of reports across labs that are never connected into a continuous timeline.
          </p>
        </div>
        <div className="p-6 bg-slate-900/90 rounded-2xl border border-slate-800 space-y-3">
          <span className="text-3xl font-black text-amber-400">02</span>
          <h4 className="font-bold text-white text-base">Unchecked Hallucinations</h4>
          <p className="text-xs text-slate-400 leading-relaxed">
            Generic LLM wrappers invent medical reference intervals, hallucinate disease diagnoses, and output arbitrary triage urgency scores without clinical grounding.
          </p>
        </div>
        <div className="p-6 bg-slate-900/90 rounded-2xl border border-slate-800 space-y-3">
          <span className="text-3xl font-black text-cyan-400">03</span>
          <h4 className="font-bold text-white text-base">Zero Provenance</h4>
          <p className="text-xs text-slate-400 leading-relaxed">
            Doctors cannot tell which numbers came from the lab document, what was reported by the patient, or what was generated by an AI model.
          </p>
        </div>
      </div>
    )
  },
  {
    number: 2,
    tag: "THE INDUSTRY GAP",
    title: "Every Tool Reads One Report; No One Reads Across Time",
    subtitle: "Why existing OCR and health apps fail clinical reality.",
    content: (
      <div className="p-8 bg-slate-900/80 rounded-2xl border border-slate-800 my-6 space-y-6">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div className="space-y-3 border-l-2 border-rose-500/60 pl-4">
            <h4 className="font-bold text-rose-400 text-sm uppercase">Current Tools (OCR & LLM Readers)</h4>
            <ul className="text-xs text-slate-300 space-y-2 list-disc list-inside">
              <li>Parses a single image in a vacuum with zero historical memory.</li>
              <li>Fake confidence scores that reflect model self-confidence, not biological reality.</li>
              <li>Opaque citations without verified OCR line bounding box grounding.</li>
              <li>Premature disease labeling that induces patient anxiety and clinical liability.</li>
            </ul>
          </div>
          <div className="space-y-3 border-l-2 border-emerald-500 pl-4">
            <h4 className="font-bold text-emerald-400 text-sm uppercase">The MedLens Paradigm</h4>
            <ul className="text-xs text-slate-200 space-y-2 list-disc list-inside">
              <li><strong>Longitudinal Patient Memory:</strong> Reconstructs years of multi-lab trends.</li>
              <li><strong>Grounded Bounding Boxes:</strong> Real OCR pixel alignment or honest unconfirmed status.</li>
              <li><strong>3-Tier Provenance Badges:</strong> Patient vs Extracted vs AI on every data point.</li>
              <li><strong>Adversarial Clinical Safety:</strong> Non-diagnostic summaries with gated counter-arguments.</li>
            </ul>
          </div>
        </div>
      </div>
    )
  },
  {
    number: 3,
    tag: "CORE INSIGHT",
    title: "“Reports are Memories. We Read All of Them.”",
    subtitle: "Showing exactly where every number came from, across time.",
    content: (
      <div className="my-10 p-10 bg-gradient-to-br from-emerald-950/40 via-slate-900 to-slate-950 rounded-3xl border border-emerald-500/30 text-center space-y-6 shadow-2xl">
        <div className="w-16 h-16 rounded-2xl bg-emerald-500/10 border border-emerald-500/30 flex items-center justify-center mx-auto text-emerald-400">
          <Sparkles className="w-8 h-8" />
        </div>
        <blockquote className="text-2xl sm:text-3xl font-black text-white max-w-2xl mx-auto leading-snug font-display">
          “Reports are memories. We read all of them — and we show you exactly where every single number came from.”
        </blockquote>
        <p className="text-xs text-emerald-400 font-mono">
          STRUCTURED • UNDERSTANDABLE • REVIEWABLE
        </p>
      </div>
    )
  },
  {
    number: 4,
    tag: "PRODUCT ARCHITECTURE",
    title: "The 4-Layer MedLens Engine",
    subtitle: "End-to-end technical pipeline from raw image bytes to FHIR R4 interoperability.",
    content: (
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 my-6">
        <div className="p-5 bg-slate-900 rounded-2xl border border-slate-800 space-y-2">
          <span className="text-xs font-mono text-emerald-400 font-bold">LAYER 1</span>
          <h4 className="font-bold text-white text-sm">Vision Ingestion & Proof</h4>
          <p className="text-xs text-slate-400 leading-relaxed">
            Multi-modal Gemini Vision + Document OCR. SHA-256 tamper-evident hashing + pixel coordinate grounding.
          </p>
        </div>
        <div className="p-5 bg-slate-900 rounded-2xl border border-slate-800 space-y-2">
          <span className="text-xs font-mono text-teal-400 font-bold">LAYER 2</span>
          <h4 className="font-bold text-white text-sm">Ontology & Sanity</h4>
          <p className="text-xs text-slate-400 leading-relaxed">
            Official NLM LOINC Clinical Tables API + RxNorm live normalization. 3-tier biological range validation.
          </p>
        </div>
        <div className="p-5 bg-slate-900 rounded-2xl border border-slate-800 space-y-2">
          <span className="text-xs font-mono text-cyan-400 font-bold">LAYER 3</span>
          <h4 className="font-bold text-white text-sm">Temporal Intelligence</h4>
          <p className="text-xs text-slate-400 leading-relaxed">
            Multi-marker correlation engine (TSH + Lipid, eGFR + Creatinine). Velocity shift detection across time.
          </p>
        </div>
        <div className="p-5 bg-slate-900 rounded-2xl border border-slate-800 space-y-2">
          <span className="text-xs font-mono text-indigo-400 font-bold">LAYER 4</span>
          <h4 className="font-bold text-white text-sm">Adversarial Safety & Delivery</h4>
          <p className="text-xs text-slate-400 leading-relaxed">
            Dual-LLM adversary red-team guardrails. HL7 FHIR R4 & ABDM NRCeS exports + Twilio WhatsApp dispatch.
          </p>
        </div>
      </div>
    )
  },
  {
    number: 5,
    tag: "FEATURE DEEP DIVE",
    title: "Grounding: Showing the Proof",
    subtitle: "Independent OCR line matching with pixel-accurate SVG overlays.",
    content: (
      <div className="p-8 bg-slate-900/90 rounded-2xl border border-slate-800 my-6 space-y-4">
        <p className="text-sm text-slate-300 leading-relaxed">
          Unlike ordinary LLM parsers where bounding boxes are self-invented guesses, MedLens performs independent OCR line matching against the original scan.
        </p>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 pt-2">
          <div className="p-4 bg-slate-950 rounded-xl border border-slate-800 space-y-1">
            <span className="text-emerald-400 font-bold text-xs">✓ Grounded Values</span>
            <p className="text-xs text-slate-400">Green highlight overlay drawn directly on top of the original lab document image.</p>
          </div>
          <div className="p-4 bg-slate-950 rounded-xl border border-slate-800 space-y-1">
            <span className="text-amber-400 font-bold text-xs">⚠️ Honest Ungrounded</span>
            <p className="text-xs text-slate-400">If text line has no clear coordinate match, honestly flags 'Location unconfirmed' without inventing coordinates.</p>
          </div>
          <div className="p-4 bg-slate-950 rounded-xl border border-slate-800 space-y-1">
            <span className="text-cyan-400 font-bold text-xs">🔒 Tamper-Proof</span>
            <p className="text-xs text-slate-400">Cryptographic SHA-256 hash computed on upload proves original document integrity.</p>
          </div>
        </div>
      </div>
    )
  },
  {
    number: 6,
    tag: "FEATURE DEEP DIVE",
    title: "Temporal Memory & Cross-Analyte Correlations",
    subtitle: "Tracking trends across time to detect concordant shifts before symptoms emerge.",
    content: (
      <div className="p-8 bg-slate-900/90 rounded-2xl border border-slate-800 my-6 space-y-6">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="p-5 bg-slate-950 rounded-xl border border-slate-800 space-y-2">
            <div className="flex items-center gap-2 text-emerald-400 text-sm font-bold">
              <TrendingUp className="w-4 h-4" />
              <span>Multi-Marker Concordance</span>
            </div>
            <p className="text-xs text-slate-300 leading-relaxed">
              When TSH rises + Total Cholesterol rises simultaneously across 3 visits, MedLens correlates them as a coupled metabolic axis shift.
            </p>
          </div>
          <div className="p-5 bg-slate-950 rounded-xl border border-slate-800 space-y-2">
            <div className="flex items-center gap-2 text-cyan-400 text-sm font-bold">
              <Activity className="w-4 h-4" />
              <span>Velocity Shift Detection</span>
            </div>
            <p className="text-xs text-slate-300 leading-relaxed">
              Measures analyte acceleration (e.g. HbA1c moving +0.4%/quarter), alerting clinicians before formal thresholds are crossed.
            </p>
          </div>
        </div>
      </div>
    )
  },
  {
    number: 7,
    tag: "FEATURE DEEP DIVE",
    title: "Adversarial AI Safety Architecture",
    subtitle: "Dual-LLM red-teaming pipeline enforcing non-diagnostic boundaries.",
    content: (
      <div className="p-8 bg-slate-900/90 rounded-2xl border border-slate-800 my-6 space-y-6">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="p-5 bg-slate-950 rounded-xl border border-slate-800 space-y-2">
            <span className="text-xs font-mono text-emerald-400 font-bold">AGENT A: INTERPRETER</span>
            <p className="text-xs text-slate-300 leading-relaxed">
              Extracts and summarizes biomarker relationships into plain, localized language (Hindi, Telugu, English) for patients and clinicians.
            </p>
          </div>
          <div className="p-5 bg-slate-950 rounded-xl border border-slate-800 space-y-2">
            <span className="text-xs font-mono text-rose-400 font-bold">AGENT B: MEDICAL ADVERSARY</span>
            <p className="text-xs text-slate-300 leading-relaxed">
              Red-teams Agent A's output with 40+ clinical blocklist phrases and counter-prompts to suppress diagnoses and triage panic scores.
            </p>
          </div>
        </div>
      </div>
    )
  },
  {
    number: 8,
    tag: "FEATURE DEEP DIVE",
    title: "Indian Healthcare Standards (ABDM & DPDP)",
    subtitle: "Engineered specifically for India's digital health infrastructure.",
    content: (
      <div className="p-8 bg-slate-900/90 rounded-2xl border border-slate-800 my-6 space-y-4">
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          <div className="p-4 bg-slate-950 rounded-xl border border-slate-800 space-y-2">
            <span className="text-xs font-bold text-emerald-400">ABDM M3 Ready</span>
            <p className="text-xs text-slate-400">Full NRCeS DiagnosticReport profiles with ABHA ID verification namespaces.</p>
          </div>
          <div className="p-4 bg-slate-950 rounded-xl border border-slate-800 space-y-2">
            <span className="text-xs font-bold text-teal-400">DPDP Act 2023</span>
            <p className="text-xs text-slate-400">Granular consent logging and cryptographically verified Right to Erasure deletion.</p>
          </div>
          <div className="p-4 bg-slate-950 rounded-xl border border-slate-800 space-y-2">
            <span className="text-xs font-bold text-indigo-400">Multilingual Delivery</span>
            <p className="text-xs text-slate-400">WhatsApp summary dispatches in Hindi, Telugu, and English via official Twilio API.</p>
          </div>
        </div>
      </div>
    )
  },
  {
    number: 9,
    tag: "LIVE DEMONSTRATION",
    title: "1-Click Walkthrough Scenarios",
    subtitle: "Built-in interactive scenarios ready for live judge and investor evaluation.",
    content: (
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 my-6">
        <div className="p-5 bg-slate-900 rounded-2xl border border-slate-800 space-y-2">
          <span className="text-xs font-bold text-emerald-400">Scenario 1</span>
          <h4 className="font-bold text-white text-sm">Arjun Sharma</h4>
          <p className="text-xs text-slate-400">3 chronological reports showing multi-marker correlation across 12 months with SVG trend trajectory.</p>
        </div>
        <div className="p-5 bg-slate-900 rounded-2xl border border-slate-800 space-y-2">
          <span className="text-xs font-bold text-amber-400">Scenario 2</span>
          <h4 className="font-bold text-white text-sm">Kavita Patel</h4>
          <p className="text-xs text-slate-400">Missing reference interval report handled safely with honest uncertainty without hallucinating ranges.</p>
        </div>
        <div className="p-5 bg-slate-900 rounded-2xl border border-slate-800 space-y-2">
          <span className="text-xs font-bold text-rose-400">Scenario 3</span>
          <h4 className="font-bold text-white text-sm">Priya Sharma</h4>
          <p className="text-xs text-slate-400">Name mismatch safety catch preventing accidental cross-contamination of family medical records.</p>
        </div>
      </div>
    )
  },
  {
    number: 10,
    tag: "COMPETITIVE MOAT",
    title: "Why MedLens Wins",
    subtitle: "Deep-tech clinical moat compared to superficial LLM wrappers.",
    content: (
      <div className="p-8 bg-slate-900/90 rounded-2xl border border-slate-800 my-6 space-y-4">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          <div className="p-4 bg-slate-950 rounded-xl border border-slate-800 space-y-1">
            <span className="text-emerald-400 font-bold text-xs">Temporal Memory</span>
            <p className="text-xs text-slate-400">Reads patient records across time, not just single isolated PDF slips.</p>
          </div>
          <div className="p-4 bg-slate-950 rounded-xl border border-slate-800 space-y-1">
            <span className="text-cyan-400 font-bold text-xs">Grounded Proof</span>
            <p className="text-xs text-slate-400">Visual bounding boxes mapped to OCR coordinates with SVG document overlay.</p>
          </div>
          <div className="p-4 bg-slate-950 rounded-xl border border-slate-800 space-y-1">
            <span className="text-indigo-400 font-bold text-xs">Adversarial Safety</span>
            <p className="text-xs text-slate-400">Dedicated LLM adversary blocking diagnostic liability and triage risk scores.</p>
          </div>
          <div className="p-4 bg-slate-950 rounded-xl border border-slate-800 space-y-1">
            <span className="text-teal-400 font-bold text-xs">Standards Ready</span>
            <p className="text-xs text-slate-400">LOINC, RxNorm, FHIR R4, ABDM M3, and DPDP Act 2023 built-in from day one.</p>
          </div>
        </div>
      </div>
    )
  },
  {
    number: 11,
    tag: "BUSINESS & COMMERCIALIZATION",
    title: "Market Opportunity & Business Model",
    subtitle: "B2B SaaS for Diagnostic Chains, Telehealth Platforms, and Insurance Providers.",
    content: (
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 my-6">
        <div className="p-6 bg-slate-900 rounded-2xl border border-slate-800 space-y-3">
          <div className="flex items-center gap-2 text-emerald-400">
            <DollarSign className="w-5 h-5" />
            <h4 className="font-bold text-white text-sm">Diagnostic Labs</h4>
          </div>
          <p className="text-xs text-slate-400 leading-relaxed">
            API per-report pricing for diagnostic chains (Dr Lal, Metropolis, Apollo) delivering branded WhatsApp summaries with 92% patient satisfaction.
          </p>
        </div>
        <div className="p-6 bg-slate-900 rounded-2xl border border-slate-800 space-y-3">
          <div className="flex items-center gap-2 text-cyan-400">
            <Layers className="w-5 h-5" />
            <h4 className="font-bold text-white text-sm">Telehealth & EHR</h4>
          </div>
          <p className="text-xs text-slate-400 leading-relaxed">
            Plug-and-play FHIR R4 temporal patient memory widgets embedded into physician consultation workflows saving 6 minutes per intake.
          </p>
        </div>
        <div className="p-6 bg-slate-900 rounded-2xl border border-slate-800 space-y-3">
          <div className="flex items-center gap-2 text-indigo-400">
            <ShieldCheck className="w-5 h-5" />
            <h4 className="font-bold text-white text-sm">Health Insurance</h4>
          </div>
          <p className="text-xs text-slate-400 leading-relaxed">
            Automated medical underwriting history reconstruction and longitudinal risk factor tracking from historical health checks.
          </p>
        </div>
      </div>
    )
  },
  {
    number: 12,
    tag: "THE VISION",
    title: "The Universal Clinical Memory Layer",
    subtitle: "Transforming disconnected pathology into verifiable, structured intelligence.",
    content: (
      <div className="my-8 p-8 bg-gradient-to-br from-emerald-950/60 via-slate-900 to-slate-950 rounded-3xl border border-emerald-500/40 text-center space-y-6 shadow-2xl">
        <div className="w-16 h-16 rounded-2xl bg-emerald-500/20 border border-emerald-500/40 flex items-center justify-center mx-auto text-emerald-400">
          <CheckCircle2 className="w-8 h-8" />
        </div>
        <h3 className="text-2xl sm:text-3xl font-black text-white font-display">
          MedLens: Intelligence With Provenance
        </h3>
        <p className="text-xs sm:text-sm text-slate-300 max-w-xl mx-auto leading-relaxed">
          Open standard. Grounded in pixel proof. Protected by adversarial safety. Built for clinicians and patients alike.
        </p>
        <div className="flex items-center justify-center gap-3 pt-2">
          <span className="text-xs font-mono text-emerald-400 bg-emerald-500/10 px-4 py-2 rounded-xl border border-emerald-500/30 font-bold">
            Live Deployment: medlens-theta.vercel.app
          </span>
        </div>
      </div>
    )
  }
];
