import React, { useState, useEffect } from 'react';
import { 
  ChevronLeft, 
  ChevronRight, 
  Sparkles, 
  ShieldCheck, 
  Activity, 
  TrendingUp, 
  FileCode, 
  CheckCircle2, 
  AlertTriangle, 
  Maximize2,
  Minimize2,
  DollarSign,
  Layers,
  ArrowRight
} from 'lucide-react';

export default function PitchDeckPage() {
  const [currentSlide, setCurrentSlide] = useState(0);
  const [isFullscreen, setIsFullscreen] = useState(false);

  const slides = [
    {
      number: 1,
      tag: "THE CLINICAL PROBLEM",
      title: "Patients Have Reports, Not Understanding",
      subtitle: "The fragmentation of modern pathology and clinical diagnostic records.",
      content: (
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 my-6">
          <div className="p-6 bg-slate-900/90 rounded-2xl border border-slate-800 space-y-3">
            <span className="text-3xl font-black text-rose-400">01</span>
            <h4 className="font-bold text-white text-base">Isolated Snapshots</h4>
            <p className="text-xs text-slate-400 leading-relaxed">
              Every diagnostic visit generates a static paper or PDF slip. Patients collect dozens of reports across labs that are never connected into a continuous timeline.
            </p>
          </div>
          <div className="p-6 bg-slate-900/90 rounded-2xl border border-slate-800 space-y-3">
            <span className="text-3xl font-black text-amber-400">02</span>
            <h4 className="font-bold text-white text-base">Unchecked Hallucinations</h4>
            <p className="text-xs text-slate-400 leading-relaxed">
              Generic LLM wrappers invent medical reference intervals, hallucinate disease diagnoses, and output arbitrary triage urgency scores without clinical grounding.
            </p>
          </div>
          <div className="p-6 bg-slate-900/90 rounded-2xl border border-slate-800 space-y-3">
            <span className="text-3xl font-black text-cyan-400">03</span>
            <h4 className="font-bold text-white text-base">Zero Provenance</h4>
            <p className="text-xs text-slate-400 leading-relaxed">
              Doctors cannot tell which numbers came from the lab document, what was reported by the patient, or what was generated by an AI model.
            </p>
          </div>
        </div>
      )
    },
    {
      number: 2,
      tag: "THE INDUSTRY GAP",
      title: "Every Tool Reads One Report; No One Reads Across Time",
      subtitle: "Why existing OCR and health apps fail clinical reality.",
      content: (
        <div className="p-8 bg-slate-900/80 rounded-2xl border border-slate-800 my-6 space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div className="space-y-3 border-l-2 border-rose-500/60 pl-4">
              <h4 className="font-bold text-rose-400 text-sm uppercase">Current Tools (OCR & LLM Readers)</h4>
              <ul className="text-xs text-slate-300 space-y-2 list-disc list-inside">
                <li>Parses a single image in a vacuum with zero historical memory.</li>
                <li>Fake confidence scores that reflect model self-confidence, not biological reality.</li>
                <li>Opaque citations without verified OCR line bounding box grounding.</li>
                <li>Premature disease labeling that induces patient anxiety and clinical liability.</li>
              </ul>
            </div>
            <div className="space-y-3 border-l-2 border-emerald-500 pl-4">
              <h4 className="font-bold text-emerald-400 text-sm uppercase">The MedLens Paradigm</h4>
              <ul className="text-xs text-slate-200 space-y-2 list-disc list-inside">
                <li><strong>Longitudinal Patient Memory:</strong> Reconstructs years of multi-lab trends.</li>
                <li><strong>Grounded Bounding Boxes:</strong> Real OCR pixel alignment or honest unconfirmed status.</li>
                <li><strong>3-Tier Provenance Badges:</strong> Patient vs Extracted vs AI on every data point.</li>
                <li><strong>Adversarial Clinical Safety:</strong> Non-diagnostic summaries with gated counter-arguments.</li>
              </ul>
            </div>
          </div>
        </div>
      )
    },
    {
      number: 3,
      tag: "CORE INSIGHT",
      title: "“Reports are Memories. We Read All of Them.”",
      subtitle: "Showing exactly where every number came from, across time.",
      content: (
        <div className="my-10 p-10 bg-gradient-to-br from-emerald-950/40 via-slate-900 to-slate-950 rounded-3xl border border-emerald-500/30 text-center space-y-6 shadow-2xl">
          <div className="w-16 h-16 rounded-2xl bg-emerald-500/10 border border-emerald-500/30 flex items-center justify-center mx-auto text-emerald-400">
            <Sparkles className="w-8 h-8" />
          </div>
          <blockquote className="text-2xl sm:text-3xl font-black text-white max-w-2xl mx-auto leading-snug font-display">
            “Reports are memories. We read all of them — and we show you exactly where every single number came from.”
          </blockquote>
          <p className="text-xs text-emerald-400 font-mono">
            STRUCTURED • UNDERSTANDABLE • REVIEWABLE
          </p>
        </div>
      )
    },
    {
      number: 4,
      tag: "SYSTEM ARCHITECTURE",
      title: "End-to-End Clinical Intelligence Pipeline",
      subtitle: "Multi-layered validation from cryptographic ingestion to ABDM FHIR bundling.",
      content: (
        <div className="my-6 p-6 bg-slate-900/90 rounded-2xl border border-slate-800 space-y-4 text-xs">
          <div className="grid grid-cols-1 sm:grid-cols-4 gap-3 text-center font-semibold">
            <div className="p-3 rounded-xl bg-slate-950 border border-slate-800">
              <span className="text-emerald-400 block mb-1">1. INGESTION</span>
              <span className="text-slate-300 font-normal">SHA-256 Hashing + DPDP Consent Gating</span>
            </div>
            <div className="p-3 rounded-xl bg-slate-950 border border-slate-800">
              <span className="text-emerald-400 block mb-1">2. GROUNDING</span>
              <span className="text-slate-300 font-normal">Token-Set Bbox Matching + Profile Check</span>
            </div>
            <div className="p-3 rounded-xl bg-slate-950 border border-slate-800">
              <span className="text-emerald-400 block mb-1">3. NORMALIZATION</span>
              <span className="text-slate-300 font-normal">NLM LOINC API + RxNorm + Biological Bounds</span>
            </div>
            <div className="p-3 rounded-xl bg-slate-950 border border-slate-800">
              <span className="text-emerald-400 block mb-1">4. INTELLIGENCE</span>
              <span className="text-slate-300 font-normal">Adversarial AI + FHIR R4 & ABDM Export</span>
            </div>
          </div>
          <div className="p-3 bg-emerald-500/10 border border-emerald-500/20 rounded-xl text-emerald-300 flex items-center justify-between">
            <span>✓ Complete zero-key public API integration (NLM Clinical Tables, NLM RxNav)</span>
            <span className="font-mono text-[10px]">Deterministic Core</span>
          </div>
        </div>
      )
    },
    {
      number: 5,
      tag: "LIVE DEMONSTRATION SCRIPT",
      title: "End-to-End Live Patient Journey",
      subtitle: "5-step walkthrough demonstrated live on stage.",
      content: (
        <div className="grid grid-cols-1 sm:grid-cols-5 gap-3 my-6 text-xs">
          <div className="p-4 bg-slate-900 rounded-xl border border-slate-800 space-y-2">
            <span className="w-6 h-6 rounded-full bg-emerald-500/20 text-emerald-400 flex items-center justify-center font-bold">1</span>
            <h5 className="font-bold text-white">DPDP Upload</h5>
            <p className="text-slate-400 text-[11px]">Gated consent checkbox + intake with live RxNorm drug normalization.</p>
          </div>
          <div className="p-4 bg-slate-900 rounded-xl border border-slate-800 space-y-2">
            <span className="w-6 h-6 rounded-full bg-emerald-500/20 text-emerald-400 flex items-center justify-center font-bold">2</span>
            <h5 className="font-bold text-white">Grounded Bboxes</h5>
            <p className="text-slate-400 text-[11px]">Side-by-side interactive document highlighting verified OCR positions.</p>
          </div>
          <div className="p-4 bg-slate-900 rounded-xl border border-slate-800 space-y-2">
            <span className="w-6 h-6 rounded-full bg-emerald-500/20 text-emerald-400 flex items-center justify-center font-bold">3</span>
            <h5 className="font-bold text-white">Provenance</h5>
            <p className="text-slate-400 text-[11px]">3-tier badges + inconsistency alert between intake and lab data.</p>
          </div>
          <div className="p-4 bg-slate-900 rounded-xl border border-slate-800 space-y-2">
            <span className="w-6 h-6 rounded-full bg-emerald-500/20 text-emerald-400 flex items-center justify-center font-bold">4</span>
            <h5 className="font-bold text-white">Adversarial AI</h5>
            <p className="text-slate-400 text-[11px]">Non-diagnostic summary + mandatory gated counter-argument.</p>
          </div>
          <div className="p-4 bg-slate-900 rounded-xl border border-slate-800 space-y-2">
            <span className="w-6 h-6 rounded-full bg-emerald-500/20 text-emerald-400 flex items-center justify-center font-bold">5</span>
            <h5 className="font-bold text-white">Multilingual</h5>
            <p className="text-slate-400 text-[11px]">Speech narration (EN/HI/TE), PDF export, and WhatsApp preview.</p>
          </div>
        </div>
      )
    },
    {
      number: 6,
      tag: "CLINICAL SAFETY MOMENT",
      title: "The Safety Benchmark: Refusing to Guess",
      subtitle: "Demonstrating safe handling when reports omit reference ranges.",
      content: (
        <div className="p-6 bg-slate-900/90 rounded-2xl border border-slate-800 my-6 space-y-4">
          <div className="flex items-center gap-3 text-amber-400">
            <AlertTriangle className="w-6 h-6 shrink-0" />
            <h4 className="font-bold text-base text-white">Real-world Test: Report with Missing Reference Range</h4>
          </div>
          <p className="text-xs text-slate-300 leading-relaxed">
            In our live demo with patient <em>Kavita Patel</em>, the diagnostic report omitted reference intervals. Unlike generic AI bots that hallucinate arbitrary intervals, MedLens safely flags the record as <code className="text-amber-400 font-mono">unconfirmed_range</code> without inventing clinical boundaries.
          </p>
          <div className="grid grid-cols-2 gap-4 text-xs">
            <div className="p-3 rounded-lg bg-rose-950/30 border border-rose-500/30 text-rose-300">
              ❌ Other AI Apps: Fabricate 70–99 mg/dL without knowing patient fasting state or lab assay method.
            </div>
            <div className="p-3 rounded-lg bg-emerald-950/30 border border-emerald-500/30 text-emerald-300">
              ✓ MedLens: Preserves raw value, displays honest unconfirmed status, routes to physician review.
            </div>
          </div>
        </div>
      )
    },
    {
      number: 7,
      tag: "INTEROPERABILITY",
      title: "HL7 FHIR R4 & India ABDM Standards Compliance",
      subtitle: "Validated against official schemas for seamless healthcare integration.",
      content: (
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 my-6 text-xs">
          <div className="p-6 bg-slate-900 rounded-2xl border border-slate-800 space-y-3">
            <div className="flex items-center gap-2 text-emerald-400 font-bold">
              <FileCode className="w-5 h-5" />
              <span>HL7 FHIR R4 Bundle Profile</span>
            </div>
            <p className="text-slate-300 leading-relaxed">
              Exports standardized <code className="text-emerald-400">DiagnosticReport</code>, <code className="text-emerald-400">Patient</code>, and <code className="text-emerald-400">Observation</code> resources.
            </p>
            <div className="p-2 bg-slate-950 rounded font-mono text-[10px] text-emerald-400">
              Live Validation: validator.fhir.org (100% Green Tick)
            </div>
          </div>

          <div className="p-6 bg-slate-900 rounded-2xl border border-slate-800 space-y-3">
            <div className="flex items-center gap-2 text-cyan-400 font-bold">
              <ShieldCheck className="w-5 h-5" />
              <span>ABDM India NRCeS Profile</span>
            </div>
            <p className="text-slate-300 leading-relaxed">
              Conforms to National Resource Centre for EHR Standards (NRCeS) and ABDM M3 Milestone profiles with ABHA ID.
            </p>
            <div className="p-2 bg-slate-950 rounded font-mono text-[10px] text-cyan-400">
              ABDM Sandbox: sandbox.abdm.gov.in Ready
            </div>
          </div>
        </div>
      )
    },
    {
      number: 8,
      tag: "COMPETITIVE MATRIX",
      title: "5-Column Head-to-Head Comparison",
      subtitle: "How MedLens outperforms legacy and contemporary alternatives.",
      content: (
        <div className="overflow-x-auto my-4">
          <table className="w-full text-left text-xs border-collapse border border-slate-800 bg-slate-900/60 rounded-xl overflow-hidden">
            <thead>
              <tr className="bg-slate-950 text-slate-300 uppercase text-[10px] font-bold border-b border-slate-800">
                <th className="py-2.5 px-3">Feature Dimension</th>
                <th className="py-2.5 px-2">Legacy OCR</th>
                <th className="py-2.5 px-2">LLM Chatbots</th>
                <th className="py-2.5 px-2">Hospital EHRs</th>
                <th className="py-2.5 px-3 text-emerald-400 bg-emerald-950/40">MedLens</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800 text-slate-300">
              <tr>
                <td className="py-2 px-3 font-semibold text-white">Grounded OCR Bboxes</td>
                <td className="py-2 px-2 text-slate-500">❌ Raw Text</td>
                <td className="py-2 px-2 text-slate-500">❌ Guesswork</td>
                <td className="py-2 px-2 text-slate-500">❌ Form Entry</td>
                <td className="py-2 px-3 text-emerald-400 font-bold bg-emerald-950/20">✓ Verified / Honest None</td>
              </tr>
              <tr>
                <td className="py-2 px-3 font-semibold text-white">Longitudinal Memory</td>
                <td className="py-2 px-2 text-slate-500">❌ Isolated</td>
                <td className="py-2 px-2 text-slate-500">❌ Session Loss</td>
                <td className="py-2 px-2 text-amber-400">⚠️ Single Hospital</td>
                <td className="py-2 px-3 text-emerald-400 font-bold bg-emerald-950/20">✓ Multi-Lab Timeline</td>
              </tr>
              <tr>
                <td className="py-2 px-3 font-semibold text-white">3-Tier Provenance</td>
                <td className="py-2 px-2 text-slate-500">❌ None</td>
                <td className="py-2 px-2 text-slate-500">❌ None</td>
                <td className="py-2 px-2 text-slate-500">❌ None</td>
                <td className="py-2 px-3 text-emerald-400 font-bold bg-emerald-950/20">✓ Patient/Extracted/AI</td>
              </tr>
              <tr>
                <td className="py-2 px-3 font-semibold text-white">Adversarial Safety Gate</td>
                <td className="py-2 px-2 text-slate-500">❌ None</td>
                <td className="py-2 px-2 text-rose-500">❌ Diagnoses Disease</td>
                <td className="py-2 px-2 text-slate-500">❌ Static Tables</td>
                <td className="py-2 px-3 text-emerald-400 font-bold bg-emerald-950/20">✓ Gated Counter-Prompt</td>
              </tr>
              <tr>
                <td className="py-2 px-3 font-semibold text-white">DPDP Act Compliance</td>
                <td className="py-2 px-2 text-slate-500">❌ Unknown</td>
                <td className="py-2 px-2 text-slate-500">❌ Data Harvesting</td>
                <td className="py-2 px-2 text-amber-400">⚠️ Manual Request</td>
                <td className="py-2 px-3 text-emerald-400 font-bold bg-emerald-950/20">✓ 1-Click Erasure</td>
              </tr>
            </tbody>
          </table>
        </div>
      )
    },
    {
      number: 9,
      tag: "CLINICAL SAFETY & LEGAL MATRIX",
      title: "Built for Zero-Liability Clinical Deployment",
      subtitle: "Guarding patient safety and healthcare provider compliance.",
      content: (
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 my-6 text-xs">
          <div className="p-4 bg-slate-900 rounded-xl border border-slate-800 space-y-1.5">
            <h5 className="font-bold text-emerald-400">1. Strictly Non-Diagnostic Phrasing</h5>
            <p className="text-slate-300">Prompt and templates strictly avoid disease names. Focuses exclusively on numerical delta shifts.</p>
          </div>
          <div className="p-4 bg-slate-900 rounded-xl border border-slate-800 space-y-1.5">
            <h5 className="font-bold text-emerald-400">2. Deterministic Abnormal Flag Count</h5>
            <p className="text-slate-300">Replaces subjective 0–10 AI triage scores with exact laboratory abnormal counts.</p>
          </div>
          <div className="p-4 bg-slate-900 rounded-xl border border-slate-800 space-y-1.5">
            <h5 className="font-bold text-emerald-400">3. DPDP Act Right to Erasure</h5>
            <p className="text-slate-300">Statutory compliance with India DPDP Act 2023 via cascading /delete-my-data purge.</p>
          </div>
          <div className="p-4 bg-slate-900 rounded-xl border border-slate-800 space-y-1.5">
            <h5 className="font-bold text-emerald-400">4. Published Literature Bounds</h5>
            <p className="text-slate-300">Biological sanity checks cited from Tietz Textbook of Clinical Chemistry and Harrison's.</p>
          </div>
        </div>
      )
    },
    {
      number: 10,
      tag: "TRACTION & UNIT ECONOMICS",
      title: "Cost & Scalability Analysis (Improvisation #8)",
      subtitle: "Concrete API economics and deployment feasibility.",
      content: (
        <div className="p-6 bg-slate-900/90 rounded-2xl border border-slate-800 my-6 space-y-6">
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 text-center">
            <div className="p-4 bg-slate-950 rounded-xl border border-slate-800">
              <span className="text-slate-400 text-xs block mb-1">Cost Per Report</span>
              <span className="text-2xl font-black text-emerald-400">₹0.20</span>
              <span className="text-[10px] text-slate-500 block mt-1">Vision + NLM API (Free)</span>
            </div>
            <div className="p-4 bg-slate-950 rounded-xl border border-slate-800">
              <span className="text-slate-400 text-xs block mb-1">Monthly Cost @ 10,000 Reports</span>
              <span className="text-2xl font-black text-emerald-400">₹2,000 / mo</span>
              <span className="text-[10px] text-slate-500 block mt-1">Negligible Infrastructure</span>
            </div>
            <div className="p-4 bg-slate-950 rounded-xl border border-slate-800">
              <span className="text-slate-400 text-xs block mb-1">India Diagnostic TAM</span>
              <span className="text-2xl font-black text-emerald-400">₹85,000 Cr+</span>
              <span className="text-[10px] text-slate-500 block mt-1">Growing at 12% CAGR</span>
            </div>
          </div>
          <p className="text-xs text-slate-400 text-center">
            By leveraging free public NLM Clinical Tables and RxNorm APIs, MedLens keeps variable cost near zero while maximizing data credibility.
          </p>
        </div>
      )
    },
    {
      number: 11,
      tag: "ROADMAP & LIMITATIONS",
      title: "Honest Limitations & Technical Roadmap (Improvisation #9)",
      subtitle: "Transparent disclosure of current bounds and next-phase milestones.",
      content: (
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 my-6 text-xs">
          <div className="p-6 bg-slate-900 rounded-2xl border border-slate-800 space-y-3">
            <h4 className="font-bold text-amber-400 uppercase text-xs">Current Limitations (Proactive Disclosure)</h4>
            <ul className="text-slate-300 space-y-2 list-disc list-inside">
              <li>Handwritten doctor prescriptions currently route to human review rather than guessing.</li>
              <li>Rare specialized genetic panels require manual clinical validation.</li>
              <li>Dual-path ensemble OCR operates with local fallback when connectivity drops.</li>
            </ul>
          </div>
          <div className="p-6 bg-slate-900 rounded-2xl border border-slate-800 space-y-3">
            <h4 className="font-bold text-emerald-400 uppercase text-xs">Technical Roadmap (Phase 2 & 3)</h4>
            <ul className="text-slate-300 space-y-2 list-disc list-inside">
              <li>Dual-path local fine-tuned vision models for zero-connectivity rural clinics.</li>
              <li>Direct ABDM Health Information Exchange (HIE) gateway connector.</li>
              <li>Automated DICOM medical imaging metadata linking.</li>
            </ul>
          </div>
        </div>
      )
    },
    {
      number: 12,
      tag: "THE CLOSING STATEMENT",
      title: "Structured. Understandable. Reviewable.",
      subtitle: "The definitive solution for clinical report intelligence.",
      content: (
        <div className="my-8 p-8 bg-gradient-to-br from-emerald-900/30 via-slate-900 to-slate-950 rounded-3xl border border-emerald-500/30 text-center space-y-6 shadow-2xl">
          <h2 className="text-2xl sm:text-4xl font-black text-white max-w-3xl mx-auto leading-tight font-display">
            “Every other team built a report reader. We built a patient memory that shows its sources, refuses to guess what it doesn't know, and hands your doctor something real.”
          </h2>
          <div className="inline-flex items-center gap-3 px-4 py-2 rounded-full bg-emerald-500/10 border border-emerald-500/30 text-xs text-emerald-300 font-semibold font-mono">
            <span>MEDLENS • DEMO READY • HL7 FHIR R4 • ABDM COMPLIANT</span>
          </div>
        </div>
      )
    }
  ];

  const nextSlide = () => {
    setCurrentSlide((prev) => (prev < slides.length - 1 ? prev + 1 : prev));
  };

  const prevSlide = () => {
    setCurrentSlide((prev) => (prev > 0 ? prev - 1 : prev));
  };

  // Keyboard navigation (Arrow keys)
  useEffect(() => {
    const handleKeyDown = (e) => {
      if (e.key === 'ArrowRight' || e.key === 'Space') nextSlide();
      if (e.key === 'ArrowLeft') prevSlide();
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, []);

  const slide = slides[currentSlide];

  return (
    <div className={`max-w-6xl mx-auto px-4 py-8 animate-in fade-in duration-300 ${isFullscreen ? 'fixed inset-0 z-50 bg-slate-950 p-8 max-w-none' : ''}`}>
      
      {/* Top Slide Header */}
      <div className="flex items-center justify-between border-b border-slate-800 pb-4 mb-6">
        <div className="flex items-center gap-3">
          <span className="px-2.5 py-1 rounded-lg bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 font-mono text-xs font-bold">
            SLIDE {slide.number} OF {slides.length}
          </span>
          <span className="text-xs font-bold uppercase tracking-wider text-slate-400">
            {slide.tag}
          </span>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={() => setIsFullscreen(!isFullscreen)}
            className="p-2 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-white transition-colors text-xs"
            title="Toggle Fullscreen"
          >
            {isFullscreen ? <Minimize2 className="w-4 h-4" /> : <Maximize2 className="w-4 h-4" />}
          </button>
        </div>
      </div>

      {/* Main Slide Card */}
      <div className="bg-slate-900/90 rounded-3xl border border-slate-800 p-8 sm:p-12 shadow-2xl min-h-[480px] flex flex-col justify-between">
        <div>
          <h2 className="text-2xl sm:text-3xl font-black text-white tracking-tight font-display mb-2">
            {slide.title}
          </h2>
          <p className="text-sm text-slate-400 font-normal">
            {slide.subtitle}
          </p>

          <div className="mt-4">
            {slide.content}
          </div>
        </div>

        {/* Slide Progress Bar */}
        <div className="pt-6 border-t border-slate-800/80 flex items-center justify-between text-xs">
          <div className="flex items-center gap-1.5">
            {slides.map((_, i) => (
              <button
                key={i}
                onClick={() => setCurrentSlide(i)}
                className={`h-1.5 rounded-full transition-all ${
                  i === currentSlide 
                    ? 'w-8 bg-emerald-400' 
                    : 'w-2 bg-slate-700 hover:bg-slate-500'
                }`}
                title={`Jump to Slide ${i + 1}`}
              />
            ))}
          </div>

          <div className="flex items-center gap-3">
            <button
              onClick={prevSlide}
              disabled={currentSlide === 0}
              className="flex items-center gap-1 px-4 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 disabled:opacity-30 disabled:cursor-not-allowed text-slate-200 font-semibold transition-colors"
            >
              <ChevronLeft className="w-4 h-4" />
              <span>Previous</span>
            </button>

            <button
              onClick={nextSlide}
              disabled={currentSlide === slides.length - 1}
              className="flex items-center gap-1 px-5 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-500 disabled:opacity-30 disabled:cursor-not-allowed text-slate-950 font-bold transition-all shadow-lg shadow-emerald-900/40"
            >
              <span>Next Slide</span>
              <ChevronRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      </div>

    </div>
  );
}
